# Generated by Django 3.1.2 on 2020-10-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201013_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
